version: "3.9"

services:
  db:
    image: postgres
    container_name: ms-order-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"