version: '3'
services:
  ms-payment:
    image: mongo:latest
    container_name: ms-payment
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ms-payment
